#! /usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;
use File::Slurp;

my $path_prefix = '/etc/hostfiles/';
my $hostfile_path = '/etc/hosts';

my @enabled = ();
my @disabled = ();

GetOptions(
	"enable=s" => \@enabled,
	"disable=s" => \@disabled,
);

@enabled = split(/,/, join(',', @enabled));
@disabled = split(/,/, join(',', @disabled));

my $hostfile = read_file($hostfile_path);

foreach my $disable (@disabled)
{
	print "Disabling $disable\n";
	$hostfile =~ s/(?:#+[\r\n])?#+\s*BEGIN: $disable[\r\n](?:#+[\r\n])?.*(?:#+[\r\n])?#+\s*END: $disable[\r\n](?:#+[\r\n])?//mgs;
}

foreach my $enable (@enabled)
{
	my $filename = $path_prefix . $enable;
	next unless (-e $filename);

	print "Enabling $enable\n";
	$hostfile =~ s/(?:#+[\r\n])?#+\s*BEGIN: $enable[\r\n](?:#+[\r\n])?.*(?:#+[\r\n])?#+\s*END: $enable[\r\n](?:#+[\r\n])?//mgs;

	my $addition = read_file($filename);
	$hostfile .= "# BEGIN: $enable\n$addition\n# END: $enable\n";
}

write_file($hostfile_path, $hostfile);
